services:
  database:
    image: postgres:17
    restart: always
    container_name: database-plans
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: plans
    ports:
      - 5432:5432
  api:
    build: 
      context: .
    container_name: app-plans
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://admin:admin@database:5432/plans?schema=public
  
